name: Login Orange HRM Demo con Playwright y Serenity JS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      login:
        description: 'Usuario para el login'
        required: true
        default: 'Admin'
      password:
        description: 'Password para el login'
        required: true
        default: 'admin123'
      test_case:
        type: choice
        description: 'Caso de prueba específico (dejar vacío para todos)'
        required: true
        default: '@loginExitoso'
        options:
          - '@loginExitoso'
          - '@mensajeError'
          - '@logout'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright + Serenity JS Tests
        env:
          TEST_USER: ${{ github.event.inputs.login || 'Admin'}}
          TEST_PASS: ${{ github.event.inputs.password|| 'admin123' }}
          TEST_CASE: ${{ github.event.inputs.test_case  || '@loginExitoso' }}
        run: |
          npm test -- --grep "$TEST_CASE"

      - name: Generate Serenity BDD Report
        if: always()
        run: npm run report 

      - name: Upload Playwright Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/ 
          retention-days: 30

      - name: Upload Serenity BDD Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-bdd-report
          path: target/site/serenity/ 
          retention-days: 90